version: "3.6"
services:
  registermaschine:
    build: .
    container_name: registermaschine
    restart: unless-stopped
  proxy:
    image: caddy:2-alpine
    container_name: proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - registermaschine
    restart: unless-stopped
